name: ggrow_together
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  shared_preferences: ^2.0.15
  http: ^1.2.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.9
  carousel_slider: ^5.0.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  geocoding: ^2.0.0
  turf: ^0.0.2
  geodesy: ^0.10.2
  google_maps_flutter: ^2.2.0 # أو أحدث إصدار

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - image/olive_background.jpeg
    - image/welcome.png
    - image/dis.png
    - profilephoto/default-profile-photo.jpg
    - image/land1.jpg
    - image/land2.jpg
    - image/gurantee.png
    - image/defaultland.png
    - image/normalland.png